---
- name: "CliXX DB Deployment Ansible Playbook"
  hosts: localhost
  connection: local
  vars:
    instance_id: wordpressdbclixxjenkins
    db_snapshot: arn:aws:rds:us-east-1:579750808937:snapshot:clixx-retail-db-snapshot-tf
    security_group: sg-03161d13f8df2aa2d
    subnet_group: clixx-db-subnet-group
  tasks:
    - name: Restore DB from snapshot
      amazon.aws.rds_instance:
        state: present
        creation_source: snapshot
        db_instance_identifier: '{{ instance_id }}'
        db_snapshot_identifier: '{{ db_snapshot }}'
        engine: mysql
        region: us-east-1
        db_instance_class: db.t3.micro
        db_subnet_group_name: '{{ subnet_group }}'
        vpc_security_group_ids:
          - '{{ security_group }}'
        wait: yes
